import os
import random
from flask import Flask, request, render_template_string, jsonify
import cloudinary
import cloudinary.uploader
import cloudinary.api

app = Flask(__name__)

# Настройки связи с твоим облаком Cloudinary
cloudinary.config(
  cloud_name = "dkk8iqf6p",
  api_key = "946533445816386",
  api_secret = "utBQxo1xonoZiY1E9zI_I6e-Bvk",
  secure = True
)

SECRET_TOKEN = "my_art_installation_secret_2026"

# Элементы концепта, которые сайт будет хаотично перемешивать при каждом обновлении
MANIFESTO_FRAGMENTS = [
    # Мишель Фуко (Дисциплинарное общество, невидимый надзор)
    "he who is subjected to a field of visibility, and who knows it, assumes responsibility for the constraints of power.",
    "the panopticon is a machine for dissociating the see/being seen dyad.",
    "visibility is a trap constructed by architectural mechanisms of subjection.",
    "power is tolerable only on condition that it masks a substantial part of itself.",
    
    # Жан Бодрийяр (Симуляция, исчезновение реальности)
    "the transition from signs that conceal something to signs that conceal that there is nothing.",
    "it is no longer a question of imitation, nor duplication, nor even parody. it is a question of substituting the signs of the real for the real.",
    "the desert of the real itself is generated by the liquidation of all referentials.",
    "control is a simulation of order designed to mask the terrifying absence of meaning.",
    
    # Альбер Камю (Абсурд, бунт, случайность)
    "the absurd is born of this confrontation between the human need and the unreasonable silence of the world.",
    "seeking what is true is not seeking what is desirable. look at what the void has randomly exposed.",
    "the only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.",
    "accepting the chaos of existence is the ultimate destruction of systemic tyranny.",
    
    # Жиль Делёз (Общество контроля, флуктуации)
    "we are in a generalized crisis in relation to all environments of enclosure. control is short-term and of rapid rates of turnover.",
    "man is no longer man enclosed, but man in debt. the system operates through continuous modulations.",
    "the digital eye does not judge; it modulates the infinite variations of the accidental.",
    
    # Вальтер Беньямин (Искусство, репродукция, потеря ауры)
    "that which withers in the age of mechanical reproduction is the aura of the work of art.",
    "the camera introduces us to unconscious optics as does psychoanalysis to unconscious impulses.",
    
    # Фридрих Ницше (Хаос, рождение смыслов)
    "one must still have chaos in oneself to be able to give birth to a dancing star.",
    "there are no facts, only interpretations. the apparatus records the uninterpreted element.",
    "he who fights with monsters might take care lest he thereby become a monster. and if you gaze for long into an abyss, the abyss gazes also into you.",
    
    # Жак Деррида (Деконструкция, след)
    "there is nothing outside of the text, and there is nothing inside the unrecorded gaze.",
    "the trace is not a presence but the simulacrum of a presence that dislocates itself.",
    
    # Чистая концепция ALEA
    "alea iacta est. the random interval as a tool of geopolitical sabotage.",
    "an archive that instantly forgets itself to bypass the censorship of historical consciousness."
]
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ALEA</title>
    <style>
        body { background-color: #030303; color: #a3a3a3; font-family: monospace; padding: 60px 20px; text-align: center; }
        .statement-box { max-width: 500px; margin: 0 auto 80px auto; text-align: left; border-left: 1px solid #222; padding-left: 20px; }
        h1 { font-size: 32px; font-weight: normal; letter-spacing: 12px; color: #fff; margin-bottom: 25px; }
        .statement { font-size: 12px; color: #555; text-transform: lowercase; letter-spacing: 1px; line-height: 1.8; }
        .gallery { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 30px; max-width: 1200px; margin: 0 auto; }
        .photo-card { background: #000; padding: 10px; border: 1px solid #111; }
        img { width: 100%; height: auto; filter: grayscale(100%) contrast(120%); transition: 0.5s ease; }
        img:hover { filter: grayscale(0%) contrast(100%); }
        .date { font-size: 9px; color: #222; margin-top: 10px; text-align: right; }
    </style>
</head>
<body>
    <div class="statement-box">
        <h1>ALEA</h1>
        <div class="statement">
            // {{ random_statement }}
        </div>
    </div>
    <div class="gallery">
        {% for image in images %}
        <div class="photo-card">
            <img src="{{ image.url }}" alt="alea snapshot">
            <div class="date">{{ image.created_at }}</div>
        </div>
        {% endfor %}
    </div>
</body>
</html>

@app.route('/')
def index():
    try:
        resources = cloudinary.api.resources(type="upload", prefix="installation", max_results=100)
        images = []
        sorted_resources = sorted(resources.get('resources', []), key=lambda x: x['created_at'], reverse=True)
        for res in sorted_resources:
            images.append({
                'url': res['secure_url'],
                'created_at': res['created_at'].replace('T', ' ').replace('Z', '')
            })
        return render_template_string(HTML_TEMPLATE, images=images)
    except Exception as e:
        return f"Ошибка: {str(e)}", 500

@app.route('/upload', methods=['POST'])
def upload():
    token = request.headers.get('Authorization')
    if token != f"Bearer {SECRET_TOKEN}":
        return jsonify({"error": "Unauthorized"}), 401
    if 'file' not in request.files:
        return jsonify({"error": "No file"}), 400
    file = request.files['file']
    try:
        upload_result = cloudinary.uploader.upload(file, folder="installation")
        return jsonify({"status": "success", "url": upload_result['secure_url']}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
